### ISSUE TITLE
No Euler Angles Data in the ROS Platform

### ISSUE THREAD

**Issue by ethan20120** [inertialsense/inertial_sense_ros#33]
Hi, 

Does the rostopic /ins does do not produce any Euler Angles data(roll,pitch,yaw)? It seems it only produces the quaternion data,linear twist,angular twist, and position data. 

The /ins topic output  on position is it in NED frame while the Quaternions in Sensor body frame ?

Any help will be great.

**Comment by siddirp** [comment]
The /ins Quaternion is in the body frame with respect to NED.

If you'd prefer Euler Angles, feel free to branch the repo modify the INS1_callback and the INS2_callback to return Euler angles instead of a quaternion. The INS1 message contain Euler angles but they are not published in our current ROS node implementation. See: https://docs.inertialsense.com/user-manual/com-protocol/DID-descriptions/#did_ins_1
